#!/usr/bin/env python3
"""
Event Type Code Generator
=========================

Reads the EventType enum from openapi.yaml and generates:
1. Go constants (internal/models/event_types_generated.go)
2. PHP class (smf-integration/EventTypes.php)
3. .scr reference documentation (game-scripts/EVENT_TYPES.md)
4. Normalization map for Go (internal/handlers/event_normalization_generated.go)

Usage:
    python3 tools/generate_types.py

This is the SINGLE SOURCE OF TRUTH for event types.
All code changes should be made to openapi.yaml, then regenerated.
"""

import yaml
import os
import re
from pathlib import Path
from datetime import datetime

# Paths relative to repo root
REPO_ROOT = Path(__file__).parent.parent
OPENAPI_PATH = REPO_ROOT / "opm-stats-api" / "web" / "static" / "openapi.yaml"
GO_OUTPUT_PATH = REPO_ROOT / "opm-stats-api" / "internal" / "models" / "event_types_generated.go"
GO_NORM_PATH = REPO_ROOT / "opm-stats-api" / "internal" / "handlers" / "event_normalization_generated.go"
PHP_OUTPUT_PATH = REPO_ROOT / "opm-stats-smf-integration" / "smf-mohaa" / "Sources" / "EventTypes.php"
PHP_OUTPUT_PATH_2 = REPO_ROOT / "opm-stats-web" / "plugin-src" / "smf-mohaa" / "Sources" / "EventTypes.php"
SCR_DOC_PATH = REPO_ROOT / "opm-stats-game-scripts" / "EVENT_TYPES.md"


def load_openapi():
    """Load and parse the OpenAPI spec."""
    with open(OPENAPI_PATH, 'r') as f:
        return yaml.safe_load(f)


def extract_event_types(spec):
    """Extract event types and aliases from OpenAPI spec."""
    schemas = spec.get('components', {}).get('schemas', {})
    
    # Get main enum
    event_type_schema = schemas.get('EventType', {})
    event_types = event_type_schema.get('enum', [])
    
    # Get aliases
    alias_schema = schemas.get('EventTypeAlias', {}).get('properties', {})
    aliases = {}
    for alias, mapping in alias_schema.items():
        canonical = mapping.get('const', '')
        if canonical:
            aliases[alias] = canonical
    
    return event_types, aliases


def to_go_const_name(event_type):
    """Convert event type to Go constant name (e.g., 'player_kill' -> 'EventPlayerKill')."""
    parts = event_type.split('_')
    return 'Event' + ''.join(p.capitalize() for p in parts)


def generate_go_constants(event_types, aliases):
    """Generate Go constants file."""
    timestamp = datetime.now().isoformat()
    
    lines = [
        '// Code generated by tools/generate_types.py. DO NOT EDIT.',
        f'// Generated at: {timestamp}',
        '// Source: opm-stats-api/web/static/openapi.yaml',
        '',
        'package models',
        '',
        '// EventType represents the type of game event',
        'type EventType string',
        '',
        '// Event type constants - GENERATED FROM OPENAPI SPEC',
        '// To add new event types, edit openapi.yaml and run `make generate-types`',
        'const (',
    ]
    
    # Group by category (based on comments in the list)
    current_category = None
    categories = {
        'game_': 'Game Flow',
        'match_': 'Match Lifecycle',
        'round_': 'Round Events',
        'warmup_': 'Warmup Events',
        'intermission_': 'Intermission',
        'kill': 'Combat (Core)',
        'death': 'Combat (Core)',
        'damage': 'Combat (Core)',
        'headshot': 'Combat (Core)',
        'player_pain': 'Combat (Core)',
        'player_suicide': 'Combat (Special)',
        'player_crushed': 'Combat (Special)',
        'player_telefragged': 'Combat (Special)',
        'player_roadkill': 'Combat (Special)',
        'player_bash': 'Combat (Special)',
        'player_teamkill': 'Combat (Special)',
        'weapon_': 'Weapon Events',
        'grenade_': 'Grenade Events',
        'jump': 'Movement',
        'land': 'Movement',
        'crouch': 'Movement',
        'distance': 'Movement',
        'ladder_': 'Movement',
        'player_stand': 'Movement',
        'player_spawn': 'Movement',
        'player_respawn': 'Movement',
        'player_movement': 'Movement',
        'player_use': 'Interaction',
        'player_spectate': 'Interaction',
        'player_freeze': 'Interaction',
        'player_say': 'Interaction',
        'chat': 'Interaction',
        'use': 'Interaction',
        'item_': 'Items',
        'health_': 'Items',
        'ammo_': 'Items',
        'armor_': 'Items',
        'server_': 'Server Lifecycle',
        'heartbeat': 'Server Lifecycle',
        'map_': 'Map Lifecycle',
        'team_': 'Team Events',
        'vote_': 'Vote Events',
        'client_': 'Client Events',
        'connect': 'Client Events',
        'disconnect': 'Client Events',
        'spawn': 'Client Events',
        'player_inactivity_drop': 'Client Events',
        'door_': 'World Events',
        'explosion': 'World Events',
        'actor_': 'AI/Bot Events',
        'bot_': 'AI/Bot Events',
        'objective_': 'Objective Events',
        'score_': 'Score Events',
        'teamkill_kick': 'Score Events',
        'player_auth': 'Custom Events',
        'accuracy_summary': 'Custom Events',
        'identity_claim': 'Custom Events',
        'reload': 'Aliases',
    }
    
    for event_type in event_types:
        const_name = to_go_const_name(event_type)
        lines.append(f'\t{const_name} EventType = "{event_type}"')
    
    lines.append(')')
    lines.append('')
    lines.append('// EventTypeAliases maps non-canonical event types to their canonical form.')
    lines.append('// Used at ingest time to normalize event types.')
    lines.append('var EventTypeAliases = map[string]EventType{')
    
    for alias, canonical in sorted(aliases.items()):
        canonical_const = to_go_const_name(canonical)
        lines.append(f'\t"{alias}": {canonical_const},')
    
    lines.append('}')
    lines.append('')
    
    return '\n'.join(lines)


def generate_go_normalization(aliases):
    """Generate Go normalization function."""
    timestamp = datetime.now().isoformat()
    
    lines = [
        '// Code generated by tools/generate_types.py. DO NOT EDIT.',
        f'// Generated at: {timestamp}',
        '// Source: opm-stats-api/web/static/openapi.yaml',
        '',
        'package handlers',
        '',
        'import "github.com/openmohaa/stats-api/internal/models"',
        '',
        '// normalizeEventType maps game script event types to canonical API types.',
        '// This ensures consistent event_type values in ClickHouse for querying.',
        '// GENERATED - edit openapi.yaml and run `make generate-types`',
        'func normalizeEventType(eventType models.EventType) models.EventType {',
        '\tswitch eventType {',
    ]
    
    for alias, canonical in sorted(aliases.items()):
        canonical_const = to_go_const_name(canonical)
        lines.append(f'\tcase "{alias}":')
        lines.append(f'\t\treturn models.{canonical_const}')
    
    lines.append('\tdefault:')
    lines.append('\t\treturn eventType')
    lines.append('\t}')
    lines.append('}')
    lines.append('')
    
    return '\n'.join(lines)


def to_php_const_name(event_type):
    """Convert event type to PHP constant name (e.g., 'player_kill' -> 'PLAYER_KILL')."""
    return event_type.upper()


def generate_php_class(event_types, aliases):
    """Generate PHP EventTypes class."""
    timestamp = datetime.now().isoformat()
    
    lines = [
        '<?php',
        'declare(strict_types=1);',
        '',
        '/**',
        ' * Event Type Constants',
        ' * ',
        ' * GENERATED FILE - DO NOT EDIT DIRECTLY',
        f' * Generated at: {timestamp}',
        ' * Source: opm-stats-api/web/static/openapi.yaml',
        ' * ',
        ' * To add new event types, edit openapi.yaml and run `make generate-types`',
        ' */',
        '',
        'namespace MohaaSMF;',
        '',
        '/**',
        ' * Canonical event type constants for the OpenMOHAA Stats system.',
        ' * Use these constants instead of string literals to ensure type safety.',
        ' */',
        'class EventTypes',
        '{',
    ]
    
    for event_type in event_types:
        const_name = to_php_const_name(event_type)
        lines.append(f"    public const {const_name} = '{event_type}';")
    
    lines.append('')
    lines.append('    /**')
    lines.append('     * Map of aliases to canonical event types.')
    lines.append('     * Use this for display or when receiving data from external sources.')
    lines.append('     */')
    lines.append('    public const ALIASES = [')
    
    for alias, canonical in sorted(aliases.items()):
        lines.append(f"        '{alias}' => self::{to_php_const_name(canonical)},")
    
    lines.append('    ];')
    lines.append('')
    lines.append('    /**')
    lines.append('     * Normalize an event type to its canonical form.')
    lines.append('     */')
    lines.append('    public static function normalize(string $eventType): string')
    lines.append('    {')
    lines.append('        return self::ALIASES[$eventType] ?? $eventType;')
    lines.append('    }')
    lines.append('')
    lines.append('    /**')
    lines.append('     * Check if an event type is valid (canonical or alias).')
    lines.append('     */')
    lines.append('    public static function isValid(string $eventType): bool')
    lines.append('    {')
    lines.append('        static $all = null;')
    lines.append('        if ($all === null) {')
    lines.append('            $reflection = new \\ReflectionClass(self::class);')
    lines.append('            $constants = $reflection->getConstants();')
    lines.append('            $all = array_flip(array_filter($constants, fn($v) => is_string($v) && $v !== \'\'));')
    lines.append('        }')
    lines.append('        return isset($all[$eventType]) || isset(self::ALIASES[$eventType]);')
    lines.append('    }')
    lines.append('}')
    lines.append('')
    
    return '\n'.join(lines)


def generate_scr_documentation(event_types, aliases):
    """Generate .scr event type reference documentation."""
    timestamp = datetime.now().isoformat()
    
    lines = [
        '# OpenMOHAA Event Types Reference',
        '',
        f'> **Generated at:** {timestamp}',
        '> ',
        '> **Source of Truth:** `opm-stats-api/web/static/openapi.yaml`',
        '> ',
        '> **DO NOT EDIT THIS FILE DIRECTLY** - Run `make generate-types` to regenerate.',
        '',
        '## Overview',
        '',
        'This document lists all valid event types for the OpenMOHAA Stats Tracker.',
        'When sending events via `build_base_payload`, use these exact type names.',
        '',
        '## Event Types',
        '',
        '| Event Type | Category | Description |',
        '|------------|----------|-------------|',
    ]
    
    # Simple category detection
    def get_category(event_type):
        prefixes = [
            ('game_', 'Game Flow'),
            ('match_', 'Match'),
            ('round_', 'Round'),
            ('warmup_', 'Warmup'),
            ('intermission_', 'Intermission'),
            ('weapon_', 'Weapon'),
            ('grenade_', 'Grenade'),
            ('player_', 'Player'),
            ('item_', 'Item'),
            ('health_', 'Item'),
            ('ammo_', 'Item'),
            ('armor_', 'Item'),
            ('server_', 'Server'),
            ('map_', 'Map'),
            ('team_', 'Team'),
            ('vote_', 'Vote'),
            ('client_', 'Client'),
            ('door_', 'World'),
            ('actor_', 'AI/Bot'),
            ('bot_', 'AI/Bot'),
            ('objective_', 'Objective'),
            ('score_', 'Score'),
            ('ladder_', 'Movement'),
        ]
        for prefix, category in prefixes:
            if event_type.startswith(prefix):
                return category
        
        if event_type in ['kill', 'death', 'damage', 'headshot']:
            return 'Combat'
        if event_type in ['jump', 'land', 'crouch', 'distance']:
            return 'Movement'
        if event_type in ['chat', 'use', 'connect', 'disconnect', 'spawn', 'reload']:
            return 'Alias'
        if event_type in ['explosion', 'heartbeat']:
            return 'Misc'
        
        return 'Other'
    
    for event_type in event_types:
        category = get_category(event_type)
        # Check if it's an alias
        is_alias = event_type in aliases
        note = f" → `{aliases[event_type]}`" if is_alias else ""
        lines.append(f'| `{event_type}` | {category} | {note} |')
    
    lines.append('')
    lines.append('## Aliases')
    lines.append('')
    lines.append('These event types are normalized to their canonical form at ingest:')
    lines.append('')
    lines.append('| Alias | Canonical Type |')
    lines.append('|-------|----------------|')
    
    for alias, canonical in sorted(aliases.items()):
        lines.append(f'| `{alias}` | `{canonical}` |')
    
    lines.append('')
    lines.append('## Usage in .scr Files')
    lines.append('')
    lines.append('```morpheus')
    lines.append('// ============================================================================')
    lines.append('// VALID EVENT TYPES - Use these with build_base_payload')
    lines.append('// ============================================================================')
    lines.append('')
    lines.append('// Combat events')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "kill"')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "headshot"')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "damage"')
    lines.append('')
    lines.append('// Movement events')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "jump"')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "crouch"')
    lines.append('')
    lines.append('// Match lifecycle')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "match_start"')
    lines.append('local.payload = waitthread global/tracker_common.scr::build_base_payload "match_end"')
    lines.append('```')
    lines.append('')
    lines.append('## Notes')
    lines.append('')
    lines.append('1. **`player_kill` is normalized to `kill`** at the API layer')
    lines.append('2. Always use the canonical type when querying ClickHouse')
    lines.append('3. SMF/PHP code should use `EventTypes::KILL` constant, not string literals')
    lines.append('')
    
    return '\n'.join(lines)


def main():
    print("Loading OpenAPI spec...")
    spec = load_openapi()
    
    print("Extracting event types...")
    event_types, aliases = extract_event_types(spec)
    print(f"  Found {len(event_types)} event types and {len(aliases)} aliases")
    
    print("\nGenerating Go constants...")
    go_code = generate_go_constants(event_types, aliases)
    GO_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(GO_OUTPUT_PATH, 'w') as f:
        f.write(go_code)
    print(f"  Written to: {GO_OUTPUT_PATH}")
    
    print("\nGenerating Go normalization function...")
    go_norm_code = generate_go_normalization(aliases)
    GO_NORM_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(GO_NORM_PATH, 'w') as f:
        f.write(go_norm_code)
    print(f"  Written to: {GO_NORM_PATH}")
    
    print("\nGenerating PHP class...")
    php_code = generate_php_class(event_types, aliases)
    PHP_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(PHP_OUTPUT_PATH, 'w') as f:
        f.write(php_code)
    print(f"  Written to: {PHP_OUTPUT_PATH}")
    
    # Also write to web plugin-src folder
    PHP_OUTPUT_PATH_2.parent.mkdir(parents=True, exist_ok=True)
    with open(PHP_OUTPUT_PATH_2, 'w') as f:
        f.write(php_code)
    print(f"  Written to: {PHP_OUTPUT_PATH_2}")
    
    print("\nGenerating .scr reference doc...")
    scr_doc = generate_scr_documentation(event_types, aliases)
    SCR_DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(SCR_DOC_PATH, 'w') as f:
        f.write(scr_doc)
    print(f"  Written to: {SCR_DOC_PATH}")
    
    print("\n✅ Type generation complete!")
    print("\nNext steps:")
    print("  1. Review generated files")
    print("  2. Run `go build ./...` to verify Go code compiles")
    print("  3. Commit changes to version control")


if __name__ == '__main__':
    main()
